<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Email Address_input-amount</name>
   <tag></tag>
   <elementGuidId>52f2723d-594d-4f24-8b61-f4161dd42909</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input.input-amount</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@type='email']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>1653da4f-d3c0-41c0-9582-be6e4d3028c9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>email</value>
      <webElementGuid>db45fa0d-6426-4de6-9598-e74f37049dc2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Enter Email</value>
      <webElementGuid>d5468972-6adc-497f-a465-7845a9d5a12b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>required</name>
      <type>Main</type>
      <value>required</value>
      <webElementGuid>e991ddfc-046f-4fa6-a39b-19059ec35930</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>input-amount</value>
      <webElementGuid>bcbfae96-e6d2-4122-9b95-29914984b1a0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;app&quot;)/div[1]/div[1]/div[@class=&quot;dashboard-page&quot;]/div[@class=&quot;container&quot;]/div[@class=&quot;main_dashboard&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-md-8&quot;]/div[@class=&quot;main_dashboard_inner&quot;]/form[1]/div[@class=&quot;form-table&quot;]/div[@class=&quot;label-title2&quot;]/div[@class=&quot;account_select2&quot;]/input[@class=&quot;input-amount&quot;]</value>
      <webElementGuid>3f37e9e4-c8b6-4ecc-8413-a1a2b809eb31</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@type='email']</value>
      <webElementGuid>49fe447b-7cfe-40da-83cf-96e1df1d956b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app']/div/div/div[2]/div[2]/div[2]/div/div/div/form/div/div[4]/div/input</value>
      <webElementGuid>e26bdfbb-dc28-45f5-a6dd-d2335c1ab110</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/input</value>
      <webElementGuid>72724998-9c78-4b75-b2ab-6aecfabc675c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'email' and @placeholder = 'Enter Email']</value>
      <webElementGuid>76974677-160e-4028-9eb0-e1da25e3d06f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
