<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Back_username-input</name>
   <tag></tag>
   <elementGuidId>1ce9b346-f8a9-4df2-92ae-5fd182fb65f3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input.username-input</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@type='text']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>e14671d9-e21a-4f38-a54a-1ff009b93011</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>634a0836-6a20-4665-9413-14bbea25f968</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Phone Number</value>
      <webElementGuid>a16f04d5-a337-44c4-b0ea-0f3c79ca2183</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>required</name>
      <type>Main</type>
      <value>required</value>
      <webElementGuid>f24f2058-50a7-4627-9067-a27bb4c29ac2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>username-input</value>
      <webElementGuid>bb532651-4b5d-4c3a-b10a-87bdd094bfca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;app&quot;)/div[1]/div[@class=&quot;hope-login-page&quot;]/div[@class=&quot;container&quot;]/div[@class=&quot;login_section&quot;]/div[@class=&quot;login-section&quot;]/div[@class=&quot;left-side&quot;]/form[@class=&quot;form-login&quot;]/div[@class=&quot;user-login&quot;]/div[@class=&quot;username&quot;]/input[@class=&quot;username-input&quot;]</value>
      <webElementGuid>f0db7f18-17a0-4902-867e-811340f8bfbc</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@type='text']</value>
      <webElementGuid>34dc4f7f-9aa3-4885-8585-de1fc1853ad7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app']/div/div/div[3]/div/div/div/form/div/div/input</value>
      <webElementGuid>8abfbee7-11a5-4c4d-a561-18b8daa435ba</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>95cd78dc-b3b1-4fa8-862f-852d8028669c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @placeholder = 'Phone Number']</value>
      <webElementGuid>fdcbbe0f-ad56-4150-980a-12e0e51eeef7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
