<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_Select Account 201 - 2010069089  211_d8a885</name>
   <tag></tag>
   <elementGuidId>f42c48d3-6f0d-4bc5-aaf6-d439c003c3f2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>select.account_type</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='app']/div/div/div[2]/div[2]/div[2]/div/div/div/form/div/div/div/select</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>e8abb35b-b9e4-416f-99ef-127a68230a18</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>account_type</value>
      <webElementGuid>00919412-2058-419c-a448-66d0cb1d16bf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Select Account 201 - 2010069089  211 - 2111218421 </value>
      <webElementGuid>bca99555-e527-4df8-957c-b6ff7c7fd4d8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;app&quot;)/div[1]/div[1]/div[@class=&quot;dashboard-page&quot;]/div[@class=&quot;container&quot;]/div[@class=&quot;main_dashboard&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-md-8&quot;]/div[@class=&quot;main_dashboard_inner&quot;]/form[1]/div[@class=&quot;form-table&quot;]/div[@class=&quot;label-title&quot;]/div[@class=&quot;account_select&quot;]/select[@class=&quot;account_type&quot;]</value>
      <webElementGuid>dde69106-24bc-433a-9387-10381a27e8bc</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app']/div/div/div[2]/div[2]/div[2]/div/div/div/form/div/div/div/select</value>
      <webElementGuid>4df7013c-4281-47cd-9171-208a56f82220</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Fetch From'])[1]/following::select[1]</value>
      <webElementGuid>bb48ce62-a001-4341-981b-34c79c35c612</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='MENU'])[1]/following::select[1]</value>
      <webElementGuid>5c5e3ff7-97a9-40f7-b0f3-5a1bf415fb90</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Date From'])[1]/preceding::select[1]</value>
      <webElementGuid>bda6c5b0-156e-4071-871b-9cd26f04d9c6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Date To *'])[1]/preceding::select[1]</value>
      <webElementGuid>7253e8ce-4e94-4bf0-bf27-0ea378e5f807</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//select</value>
      <webElementGuid>3e70ebe1-39bd-43d0-8850-915cb1b41c0f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[(text() = 'Select Account 201 - 2010069089  211 - 2111218421 ' or . = 'Select Account 201 - 2010069089  211 - 2111218421 ')]</value>
      <webElementGuid>bc8acaa5-9cb6-4184-b1e4-07085a17466c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
